### ISSUE TITLE
bhottu keeps voicing me when I try to remove voice

### ISSUE THREAD

**Issue by codyharrington** [gentoomen/bhottu#65]
It's pretty buggy, I think bhottu should respect when I remove voice.

I can submit a pull request to fix this if you guys don't mind

**Comment by Mechazawa** [comment]
Kek
-------- Original message --------From: Cody Harrington <notifications@github.com> Date: 02/11/2016  22:26  (GMT+01:00) To: gentoomen/bhottu <bhottu@noreply.github.com> Subject: [gentoomen/bhottu] bhottu keeps voicing me when I try to remove voice (#65) 
It's pretty buggy, I think bhottu should respect when I remove voice.
I can submit a pull request to fix this if you guys don't mind

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/gentoomen/bhottu","title":"gentoomen/bhottu","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/gentoomen/bhottu"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"bhottu keeps voicing me when I try to remove voice (#65)"}],"action":{"name":"View Issue","url":"https://github.com/gentoomen/bhottu/issues/65"}}}
